In [48]:
import pandas as pd
import numpy as np

data = {
    "Employee": ["Rahul", "Priya", "Amit", "Sneha", "Ravi",
                 "Neha", "Vijay", "Pooja", "Arjun", "Divya"],
    "Dept":     ["Sales", "Tech", "Sales", "HR", "Tech",
                 "HR", "Sales", "Tech", "Sales", "HR"],
    "City":     ["Hyderabad", "Mumbai", "Delhi", "Hyderabad", "Mumbai",
                 "Delhi", "Hyderabad", "Mumbai", "Delhi", "Hyderabad"],
    "Salary":   [45000, 72000, 51000, 38000, 85000,
                 42000, 55000, 68000, 49000, 500000],
    "Experience":[2, 5, 3, 1, 7, 2, 4, 6, 3, 2]
}

df = pd.DataFrame(data)

In [49]:
df[(df['Salary'] > 40000) & (df['Salary'] < 70000)],['Employees']

(  Employee   Dept       City  Salary  Experience
 0    Rahul  Sales  Hyderabad   45000           2
 2     Amit  Sales      Delhi   51000           3
 5     Neha     HR      Delhi   42000           2
 6    Vijay  Sales  Hyderabad   55000           4
 7    Pooja   Tech     Mumbai   68000           6
 8    Arjun  Sales      Delhi   49000           3,
 ['Employees'])

In [50]:

df[(df['City'] == "Mumbai") | (df['City'] == 'Delhi') & (df['Experience'] > 4)]

  Employee  Dept    City  Salary  Experience
1    Priya  Tech  Mumbai   72000           5
4     Ravi  Tech  Mumbai   85000           7
7    Pooja  Tech  Mumbai   68000           6

In [51]:
median_Salary = df['Salary'].median()
df[df['Salary'] > median_Salary]

  Employee   Dept       City  Salary  Experience
1    Priya   Tech     Mumbai   72000           5
4     Ravi   Tech     Mumbai   85000           7
6    Vijay  Sales  Hyderabad   55000           4
7    Pooja   Tech     Mumbai   68000           6
9    Divya     HR  Hyderabad  500000           2

In [52]:
df.sort_values('Experience', ascending=False).groupby('Dept').head(3)

  Employee   Dept       City  Salary  Experience
4     Ravi   Tech     Mumbai   85000           7
7    Pooja   Tech     Mumbai   68000           6
1    Priya   Tech     Mumbai   72000           5
6    Vijay  Sales  Hyderabad   55000           4
8    Arjun  Sales      Delhi   49000           3
2     Amit  Sales      Delhi   51000           3
5     Neha     HR      Delhi   42000           2
9    Divya     HR  Hyderabad  500000           2
3    Sneha     HR  Hyderabad   38000           1

In [53]:
df[(df['City'] == "Hyderabad") & (df['Salary'] > 50000)]

  Employee   Dept       City  Salary  Experience
6    Vijay  Sales  Hyderabad   55000           4
9    Divya     HR  Hyderabad  500000           2

In [54]:
Q1 =df['Salary'].quantile(0.25)
Q3 =df['Salary'].quantile(0.75)

In [55]:
IQR = Q3 - Q1
IQR

np.float64(25000.0)

In [56]:
lower_limit = Q1 - 2 * IQR
upper_limit = Q3 + 2 * IQR

In [57]:
lower_limit

np.float64(-4000.0)

In [58]:
df[(df["Salary"] >= lower_limit) & (df['Salary'] <= upper_limit)]

  Employee   Dept       City  Salary  Experience
0    Rahul  Sales  Hyderabad   45000           2
1    Priya   Tech     Mumbai   72000           5
2     Amit  Sales      Delhi   51000           3
3    Sneha     HR  Hyderabad   38000           1
4     Ravi   Tech     Mumbai   85000           7
5     Neha     HR      Delhi   42000           2
6    Vijay  Sales  Hyderabad   55000           4
7    Pooja   Tech     Mumbai   68000           6
8    Arjun  Sales      Delhi   49000           3

In [59]:
print(lower_limit, upper_limit)

-4000.0 121000.0

In [62]:
df.groupby("Dept")['Salary'].sum()

Dept
HR       580000
Sales    200000
Tech     225000
Name: Salary, dtype: int64

In [63]:
df.groupby('City')['Experience'].mean()

City
Delhi        2.666667
Hyderabad    2.250000
Mumbai       6.000000
Name: Experience, dtype: float64

In [65]:
df.groupby('Dept')['Salary'].agg(['min', 'max'])

         min     max
Dept
HR     38000  500000
Sales  45000   55000
Tech   68000   85000

In [66]:
df.groupby(['City', 'Dept']).count()

                 Employee  Salary  Experience
City      Dept
Delhi     HR            1       1           1
          Sales         2       2           2
Hyderabad HR            2       2           2
          Sales         2       2           2
Mumbai    Tech          3       3           3

In [67]:
df.groupby('City')['Salary'].mean().sort_values(ascending=False)

City
Hyderabad    159500.000000
Mumbai        75000.000000
Delhi         47333.333333
Name: Salary, dtype: float64