In [3]:
import pandas as pd
import numpy as np

data = {
    "Product":  ["Laptop", "Phone", "Tablet", "Laptop", 
                 "Phone", "Tablet", "Laptop", "Phone"],
    "Region":   ["North", "South", "North", "East",
                 "West", "South", "West", "North"],
    "Sales":    [85000, 45000, 32000, 91000,
                 52000, 28000, 78000, 41000],
    "Units":    [5, 8, 6, 7, 9, 4, 6, 7],
    "Month":    ["Jan", "Jan", "Jan", "Feb",
                 "Feb", "Feb", "Mar", "Mar"]
}

df = pd.DataFrame(data)
print(df)

ModuleNotFoundError: No module named 'pandas'

In [2]:
df[["Product", "Sales"]]

NameError: name 'df' is not defined

In [4]:
import pandas as pd

data = {
    "Student": ["Rahul", "Rahul", "Rahul", "Rahul",
                "Priya", "Priya", "Priya", "Priya",
                "Amit",  "Amit",  "Amit",  "Amit"],
    "Subject": ["Maths", "Science", "English", "Hindi",
                "Maths", "Science", "English", "Hindi",
                "Maths", "Science", "English", "Hindi"],
    "Sem":     [1, 1, 2, 2, 1, 1, 2, 2,
                1, 1, 2, 2],
    "Marks":   [85, 72, 90, 78,
                91, 88, 76, 82,
                78, 65, 82, 70]
}

df = pd.DataFrame(data)

In [6]:
pd.pivot_table(df, index ='Student', columns = 'Subject', values = 'Marks', aggfunc = 'sum')

Subject  English  Hindi  Maths  Science
Student
Amit          82     70     78       65
Priya         76     82     91       88
Rahul         90     78     85       72

In [8]:
pd.pivot_table(df, index='Sem', columns = 'Student', values = 'Marks' , aggfunc='mean')

Student  Amit  Priya  Rahul
Sem
1        71.5   89.5   78.5
2        76.0   79.0   84.0

In [11]:
pd.pivot_table(df, index='Subject', columns = 'Sem', values = 'Marks', aggfunc='max')

Sem         1     2
Subject
English   NaN  90.0
Hindi     NaN  82.0
Maths    91.0   NaN
Science  88.0   NaN

In [14]:
print(df[df["Subject"] != "Hindi"])

   Student  Subject  Sem  Marks
0    Rahul    Maths    1     85
1    Rahul  Science    1     72
2    Rahul  English    2     90
4    Priya    Maths    1     91
5    Priya  Science    1     88
6    Priya  English    2     76
8     Amit    Maths    1     78
9     Amit  Science    1     65
10    Amit  English    2     82

In [15]:
pd.pivot_table(df, index = 'Student', columns = 'Sem', values = 'Marks', aggfunc = 'count')

Sem      1  2
Student
Amit     2  1
Priya    2  1
Rahul    2  1

In [1]:
import pandas as pd

data = {
    "Student": ["Rahul", "Rahul", "Rahul",
                "Priya", "Priya", "Priya",
                "Amit",  "Amit",  "Amit"],
    "Subject": ["Maths", "Science", "English",
                "Maths", "Science", "English",
                "Maths", "Science", "English"],
    "Sem":     [1, 1, 2, 1, 2, 2, 1, 2, 1],
    "Marks":   [85, 72, 90, 91, 88, 76, 78, 65, 82]
}

df = pd.DataFrame(data)

In [2]:
df.groupby('Student')['Marks'].min()

Student
Amit     65
Priya    76
Rahul    72
Name: Marks, dtype: int64

In [3]:
df.groupby('Student')['Marks'].max()

Student
Amit     82
Priya    91
Rahul    90
Name: Marks, dtype: int64